// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxogevspikcuehxdfcmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b2dldnNwaWtjdWVoeGRmY21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTg5NDEsImV4cCI6MjA2NTA3NDk0MX0.X93LRgdBJ9po_AHsuFv-1RJj7VVjsypcIWkcOIRvrSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);